FROM python:3.7.4

RUN set -x \
  && echo "Setting up system..." \
  && apt-get -y update \

ADD requirements.txt /app/requirements.txt
RUN set -x \
  && echo "Installing python dependencies..." \
  && pip install -r /app/requirements.txt \
  && rm /app/requirements.txt

CMD [ "/app/IDGene.py" ]
