version: '3'
services:
  enrichrbotbert2:
    build: .
    image: maayanlab/enrichrbotbert2:1.2.5
    env_file: .env
    volumes:
      - ./output:/app/output
      - ./tweets:/app/tweets
      - ./bert/data:/app/bert/data/
      # TODO download on startup
      - ./bert/bert_output:/app/bert/bert_output
      - ./screenshots:/app/screenshots