version: '3'
services:
  replytogwasbot:
    build: .
    image: maayanlab/enrichrbot-reply-to-preprocessed-swasbot:1.1.0
    env_file: .env
    volumes:
      - ./data:/app/data
      - ./screenshots:/app/screenshots